### ISSUE TITLE
Elements (ed.lib.vt.edu) is linking to the wrong URL for VTW Dev deposits

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#287]
Hi @keithgee and @kayiwa , I've attached a screenshot of my Elements homepage below (ed.lib.vt.edu). I apologize if this issue has been discussed earlier and I've forgotten the conversation. 

In short, Elements (ed.lib.vt.edu) is linking to the wrong VTechWorksDev URL for publications that have been deposited in VTW.

To elaborate, for the publication "3D SYSTEMS INTEGRATION CONFERENCE. IEEE INTERNATIONAL. 2013. (3DIC 2013)", the VTechWorksDev URL points to http://hdl.handle.net/10919/71318, which is _not_ the correct item URL (this item's URL is http://vtechworks.dev.lib.vt.edu/handle/10919/71318).

Any ideas as to what's going on? Thanks.

<img width="895" alt="screen shot 2016-06-09 at 3 24 16 pm" src="https://cloud.githubusercontent.com/assets/5408616/15943447/1c973dba-2e57-11e6-9904-027661348ee4.png">

**Comment by keithgee** [comment]
A parameter was set incorrectly in dspace.cfg.
handle.canonical.url

This should resolve itself when Tomcat is restarted on dev to resolve the other issues.

**Comment by mello99** [comment]
Francis restarted it 32 minutes ago (and the restart didn't resolve the metadata field duplication issues). Should I ask him to restart it again?

**Comment by keithgee** [comment]
I saw production restart around that time. He might have accidentally been
on the wrong machine.

**Comment by mello99** [comment]
Ok, I asked him to restart on mattermost. Fingers crossed!

**Comment by mello99** [comment]
Tomcat was restarted and the URLs are still awry for Elements items deposited from ed.lib.vt.edu (that is, the URLs still aren't pointing to the correct locations from the Elements menu).

**Comment by keithgee** [comment]
It won't fix previously deposited items. Only new ones.

**Comment by mello99** [comment]
I see. I worked for the latest item I deposited, _victory dance_

**Comment by mello99** [comment]
Okay, the last 3 items I deposited don't have this problem anymore (since the Tomcat restart), so I'm closing this issue. Well done, folks!
