### ISSUE TITLE
Remove old About, Policies, and Help pages

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#453]
The new about, help, and policy pages are 
- https://vtechworks.lib.vt.edu/page/about
- https://vtechworks.lib.vt.edu/page/help
- https://vtechworks.lib.vt.edu/page/policies. 

Please remove or disable the old pages, 
- https://vtechworks.lib.vt.edu/page/about
- https://vtechworks.lib.vt.edu/page/help
- https://vtechworks.lib.vt.edu/page/policies.

**Comment by pgray64** [comment]
Resolved with Pull Request #455

**Comment by amandafrench** [comment]
Now, when a user manually goes to https://vtechworks.lib.vt.edu/page/policies (which still shows up in Google searches) they still get a page in the application instead of being taken to the Google Site. See screenshot. I'll put in a TeamDynamix request for a 301 redirect of that and other page URLs. 

![screenshot 2017-02-20 13 56 02](https://cloud.githubusercontent.com/assets/227453/23138294/81812196-f774-11e6-992c-c85967a871e6.png)

**Comment by amandafrench** [comment]
Have put in the request for a redirect. You can close this issue when it takes effect.

**Comment by alawvt** [comment]
@amandafrench, thanks!

**Comment by keithgee** [comment]
Redirects in effect. Closing.
